language: python
python:
  - "3.2"
  - "3.3"
# command to install dependencies
before_install:
  - "sudo apt-get install -qq libfreetype6-dev libjpeg-dev zlib1g-dev libpng12-dev"
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"    
# command to run tests
script: "mv pyroman pyroman_moved && env PYTHONPATH=.:$PYTHONPATH py.test -v ."
notifications:
  email: false
